# Group Tasks {-}

## Sampling Distributions {-}

In Part 1, we have only focused on estimating the proportion of those who think the work scientists do doesn’t benefit them.

Now, you’ll try to estimate the proportion of those who think the work of scientists does benefit them.

<br>

### Task 1 {-}

Take a sample of size 20 from the population and calculate the proportion of people in this sample who think the work scientists do enhances their lives. Using this sample, state the point estimate of the population proportion of people who think the work scientists do enhance their lives?

<br>

### Task 2 {-}

Take 2000 samples of size 20 from the population and compute 2000 sample proportions for those who think the work scientists do enhance their lives. Store these proportions as `sample_props20`. Plot the data as a histogram.

<br>

**Is there any skew in this sampling distribution?**

a)  Yes, the data are left skewed

b)  Yes, the data are right skewed

c)  No, there is no skew present

<br>

### Task 3 {-}

Change your sample size from 20 to 200 and calculate each sample proportion using the same method as above. Store these proportions in a new object called `sample_props200`. Then, plot the sampling distribution as a histogram.

<br>

**What value would you use to estimate the true population proportion from the sampling distribution from *Task 3*?**

a)  The median of the sample proportions

b)  The mean of the sample proportions

c)  The maximum of the sample proportions

d)  The minimum of the sample proportions

<br>

**Of the sampling distributions from 2 and 3, which has a smaller spread?**

a)  Sampling distribution from Q2

b)  Sampling distribution from Q3

<br>

## Confidence Intervals {-}

<br>

**For a confidence level of 90%, what is the appropriate critical value?** *(to 2 decimal places)*
`r fitb(1.64)`

<br>

### Task 4 {-}

Take a sample of size 60 from `us_adults` and find a confidence interval for the proportion of US Adults who think climate change is affecting their local community with a confidence level of 90% and interpret it.

<br>

**Is this interval narrower or wider than the confidence interval for the proportion of US Adults who think climate change is affecting their local community calculated earlier at a 95% confidence level?**

a)  narrower

b)  wider

<br>




